language: generic

sudo: required

# Only run test when committing to a master branch.
#branches:
#  only:
#    - master

env:
  globaL:
    - COMPOSE_HTTP_TIMEOUT=3600
    - AEGIR_TESTS_VERSION=master

#env:
#  - test: Ubuntu 14.04 Apache
#    distribution: ubuntu
#    version: 14.04
#    init: /sbin/init
#    run_opts: ""

addons:
  hosts:
    - aegir.local.computer
    - sitetest.aegir.local.computer

services:
  - docker

before_install:

  # Debugging users
  - whoami
  - id -u

  # upgrade docker-engine to specific version
  - git clone http://github.com/tommycox/tests.git
  - cd tests
  - git checkout $AEGIR_TESTS_VERSION
  - sudo bash travis/prepare-docker.sh

  - sudo mkdir vendor
  - sudo chmod 777 vendor

  - sudo mkdir bin
  - sudo chmod 777 bin

  - cd ..

  # First build stock image, and one for own user.
  - sudo docker build --rm -t tommycox/hostmaster .
  - sudo docker build --rm -t tommycox/hostmaster:own --build-arg AEGIR_UID=1000 .

  # Then build local image. Only difference is /var/aegir is volume.
  - sudo docker build --rm -t tommycox/hostmaster:local -f Dockerfile-local .

  # Then build test image. Only difference is CMD defaults to run-tests.sh
  - sudo docker build --rm -t tommycox/hostmaster:test -f Dockerfile-test .

  # Go to tests/travis folder. Docker-compose files are in there.
  - cd tests/travis
script:

  # Launch docker-compose.yml file within tests repo.
  - sudo docker-compose --file docker-compose-tests.yml run hostmaster
