version: '2'

# This compose file is just an example. Create your own to launch your own Aegir cluster

services:

  hostmaster:
    image: tommycox/hostmaster
    ports:
      - 80:80
    hostname: aegir.local.computer
    links:
      - database
    depends_on:
      - database
    environment:
      VIRTUAL_HOST: aegir.local.computer
      MYSQL_ROOT_PASSWORD: strongpassword

  database:
    image: mariadb
    logging:
      driver: none
    environment:
      MYSQL_ROOT_PASSWORD: strongpassword